/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProverbsRouteImport } from './routes/proverbs'
import { Route as MartyrsRouteImport } from './routes/martyrs'
import { Route as MapRouteImport } from './routes/map'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FiguresRouteImport } from './routes/figures'
import { Route as CultureRouteImport } from './routes/culture'
import { Route as CuisineRouteImport } from './routes/cuisine'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProverbsRoute = ProverbsRouteImport.update({
  id: '/proverbs',
  path: '/proverbs',
  getParentRoute: () => rootRouteImport,
} as any)
const MartyrsRoute = MartyrsRouteImport.update({
  id: '/martyrs',
  path: '/martyrs',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FiguresRoute = FiguresRouteImport.update({
  id: '/figures',
  path: '/figures',
  getParentRoute: () => rootRouteImport,
} as any)
const CultureRoute = CultureRouteImport.update({
  id: '/culture',
  path: '/culture',
  getParentRoute: () => rootRouteImport,
} as any)
const CuisineRoute = CuisineRouteImport.update({
  id: '/cuisine',
  path: '/cuisine',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cuisine': typeof CuisineRoute
  '/culture': typeof CultureRoute
  '/figures': typeof FiguresRoute
  '/gallery': typeof GalleryRoute
  '/map': typeof MapRoute
  '/martyrs': typeof MartyrsRoute
  '/proverbs': typeof ProverbsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/statistics': typeof StatisticsRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cuisine': typeof CuisineRoute
  '/culture': typeof CultureRoute
  '/figures': typeof FiguresRoute
  '/gallery': typeof GalleryRoute
  '/map': typeof MapRoute
  '/martyrs': typeof MartyrsRoute
  '/proverbs': typeof ProverbsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/statistics': typeof StatisticsRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cuisine': typeof CuisineRoute
  '/culture': typeof CultureRoute
  '/figures': typeof FiguresRoute
  '/gallery': typeof GalleryRoute
  '/map': typeof MapRoute
  '/martyrs': typeof MartyrsRoute
  '/proverbs': typeof ProverbsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/statistics': typeof StatisticsRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cuisine'
    | '/culture'
    | '/figures'
    | '/gallery'
    | '/map'
    | '/martyrs'
    | '/proverbs'
    | '/sitemap.xml'
    | '/statistics'
    | '/timeline'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cuisine'
    | '/culture'
    | '/figures'
    | '/gallery'
    | '/map'
    | '/martyrs'
    | '/proverbs'
    | '/sitemap.xml'
    | '/statistics'
    | '/timeline'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cuisine'
    | '/culture'
    | '/figures'
    | '/gallery'
    | '/map'
    | '/martyrs'
    | '/proverbs'
    | '/sitemap.xml'
    | '/statistics'
    | '/timeline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CuisineRoute: typeof CuisineRoute
  CultureRoute: typeof CultureRoute
  FiguresRoute: typeof FiguresRoute
  GalleryRoute: typeof GalleryRoute
  MapRoute: typeof MapRoute
  MartyrsRoute: typeof MartyrsRoute
  ProverbsRoute: typeof ProverbsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatisticsRoute: typeof StatisticsRoute
  TimelineRoute: typeof TimelineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proverbs': {
      id: '/proverbs'
      path: '/proverbs'
      fullPath: '/proverbs'
      preLoaderRoute: typeof ProverbsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/martyrs': {
      id: '/martyrs'
      path: '/martyrs'
      fullPath: '/martyrs'
      preLoaderRoute: typeof MartyrsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/figures': {
      id: '/figures'
      path: '/figures'
      fullPath: '/figures'
      preLoaderRoute: typeof FiguresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/culture': {
      id: '/culture'
      path: '/culture'
      fullPath: '/culture'
      preLoaderRoute: typeof CultureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuisine': {
      id: '/cuisine'
      path: '/cuisine'
      fullPath: '/cuisine'
      preLoaderRoute: typeof CuisineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CuisineRoute: CuisineRoute,
  CultureRoute: CultureRoute,
  FiguresRoute: FiguresRoute,
  GalleryRoute: GalleryRoute,
  MapRoute: MapRoute,
  MartyrsRoute: MartyrsRoute,
  ProverbsRoute: ProverbsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatisticsRoute: StatisticsRoute,
  TimelineRoute: TimelineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
